// Code generated by ent, DO NOT EDIT.

package ent

import (
	"menu-service/ent/menu"
	"menu-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescName is the schema descriptor for name field.
	menuDescName := menuFields[1].Descriptor()
	// menu.NameValidator is a validator for the "name" field. It is called by the builders before save.
	menu.NameValidator = menuDescName.Validators[0].(func(string) error)
	// menuDescPrice is the schema descriptor for price field.
	menuDescPrice := menuFields[3].Descriptor()
	// menu.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	menu.PriceValidator = menuDescPrice.Validators[0].(func(int) error)
}
